### ISSUE TITLE
mounting docker.sock via -volumes-from nginx-proxy does not work

### ISSUE THREAD

**Issue by robert-figura** [nginx-proxy/acme-companion#1021]
# Bug description

acme-companion keeps restarting with the following error message:

```
Info: running acme-companion version v2.2.7-5-gdefde43
Error: you need to share your Docker host socket with a volume at /var/run/docker.sock
Typically you should run your container with: '-v /var/run/docker.sock:/var/run/docker.sock
```

I'm running acme-companion against nginx-proxy:alpine, and the latter works fine:

```
Info: running nginx-proxy version 1.2.3-16-g7322a2d
```

I've started nginx-proxy mounting `docker.sock` to `/var/run/docker.sock:/tmp/docker.sock:ro` as described in nginx-proxy's README.md. The error message suggests that acme-companion expects the socket mounted elsewhere instead, and indeed, when I add the following flag to `docker run` it works:

```
$ docker run -v /var/run/docker.sock:/var/run/docker.sock:ro ... nginxproxy/acme-companion
```

**Comment by robert-figura** [comment]
Edited docker run command's mount target which was pointing to `/tmp/docker.sock` which is what does not work.

**Comment by robert-figura** [comment]
Apparently, README.md gives an example using the wrong path: `/tmp/docker.sock`.

But it should also just work with `--volumes-from nginx-proxy`, so it may be a good idea to also update the path nginx-proxy uses to the standard one, that is, to do the same breaking change which caused the problem with acme-companion also with nginx-proxy.

**Comment by Montana** [comment]
Hi @robert-figura, 

Attempting to utilize `-volumes-from` for sharing `docker.sock` through an `nginx-proxy` container suggests the initial mounting of `docker.sock` from the host to `nginx-proxy`. However, the purpose of `-volumes-from` is to share data volumes between containers, rather than directly sharing sockets or host-mounted files. Without `nginx-proxy` specifically establishing a volume for `docker.sock`, sharing it with another container via `-volumes-from` will not be achievable.

So you could run something like this and have this work:

```bash
docker run -d --name nginx-proxy \
  -v /var/run/docker.sock:/var/run/docker.sock \
  nginx-proxy-image

docker run -d --name another-container \
  -v /var/run/docker.sock:/var/run/docker.sock \
  another-container-image
```

In any event, you should try to mount `docker.sock` directly into each container. I hope this helps.

Cheers,
Michael Mendy

**Comment by buchdag** [comment]
@robert-figura I could not find the example with the wrong path you're referring to. Each time the path `/tmp/docker.sock` is used, it's for an nginx-proxy of docker-gen container, and each time the `/var/run/docker.sock` path is used it's for an acme-companion container, as it should be. The documentation is explicit about the fact that the two containers expect the Docker socket mounted in a different place.

@Montana explanation of why `--volumes-from` cannot work without additional effort in this case is rather clear 👍 (but  `--volumes-from` will work for sharing the other volumes like `/etc/nginx/certs`)

> it may be a good idea to also update the path nginx-proxy uses to the standard one, that is, to do the same breaking change which caused the problem with acme-companion also with nginx-proxy.

There was never any "breaking change" that introduced this, this has been the case since the first commit of both project (who where initially created by different peoples) almost ten years ago.

Updating nginx-proxy now without additional init code to automatically link the old path to the new one would break the working config of every single user. Even if I agree that the expected path of the Docker socket should ideally be the same in both container, I don't think the reward of doing this is worth the effort and most importantly the risk to existing users.
