### ISSUE TITLE
letsencrypt-nginx-proxy-companion    | ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Invalid character in DNS name

### ISSUE THREAD

**Issue by Rocks360** [nginx-proxy/acme-companion#154]
Hello, 

I get this Error when I try to generate test certs. Error:

> letsencrypt-nginx-proxy-companion    | ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Invalid character in DNS name

My domain is a german IDN domain for example: IDN-Form: überall-ist.de  => ACE-String: xn--berall-ist-8db.de 
See this link https://www.denic.de/wissen/idn-domains/

Is it a problem of the letsencrypt-nginx-proxy-companion software or do I need to write a mail to the letsencrypt team?

**Comment by cpu** [comment]
> or do I need to write a mail to the letsencrypt team?

Wanted to leave a pointer for any wayward souls that find this thread first, since [we answered it in the community forum](https://community.letsencrypt.org/t/invalid-character-in-dns-name-on-german-domains-with-special-characters/26221/2): Let's Encrypt does support IDN domains but they must be provided in A-label (also known as ACE) form.

**Comment by cowai** [comment]
Has any gotten this container to work with IDN names? I get the exact same error with a norwegian character.
