### ISSUE TITLE
How can I disable http2?

### ISSUE THREAD

**Issue by nt-jjrubio** [nginx-proxy/acme-companion#770]
When I use the HTTP2 protocol, the headers arrive empty, if I force to use HTTP1.1 it works correctly.

**Comment by buchdag** [comment]
Hi. Could you please follow the repository's bug template ?

Bug description
-----------------
A clear and concise description of what the bug is, with steps to reproduce.

letsencrypt-nginx-proxy-companion image version
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```bash
[you@yourhost]: $ docker logs companion-container-name
Info: running letsencrypt-nginx-proxy-companion version v2.0.0
[...]
```

If this first log line isn't present you are using a `v1` image: please provide the [tagged version](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/releases) you are using. If you are using `latest`, please try again with a tagged release before opening an issue (the last `v1` tagged release is `v1.13.1`).

nginx-proxy-companion configuration
-----------------

Please provide the configuration (either command line, compose file, or other) of your nginx-proxy stack and your proxied container(s).

You can obfuscate information you want to keep private (and should obfuscate configuration secrets) such as domain(s) and/or email adress(es), but other than that **please provide the full configurations** and not the just snippets of the parts that seem relevants to you.

Containers logs
-----------------

Please provide the logs of:
- your `letsencrypt-nginx-proxy-companion` container
- your `nginx-proxy` container (or `nginx` and `docker-gen` container in a three containers setup)

`docker logs name-of-the-container`

Docker host
-----------------

 - OS: [e.g. Ubuntu 20.04]
 - Docker version: output of `docker version`

**Comment by buchdag** [comment]
No answer from issue creator, closing.
